services:
  notes-app:
    build: .
    container_name: yisusnotes
    ports:
      - "3000:3000"
    volumes:
      - yisus_notes_db:/app/prisma
    restart: always
    environment:
      - NODE_ENV=production

volumes:
  yisus_notes_db:
